imports:
    - { resource: security.yml }
#    - { resource: parameters.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%symforium.core_dir%/Application/config/routing.yml"
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    http_method_override: true
    translator: ~
    session: ~
    form: ~
    csrf_protection: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                connection: default

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

white_october_breadcrumbs:
    separator: '>'

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Symforium\Core\Bundle\CoreBundle\Entity\User

#knp_menu:
#    twig:
#        template: SctrCmsMainBundle:Layout:menu.html.twig

#aequasi_cache:
#    instances:
#        default:
#            type: redis
#            hosts: %cache.redis.hosts%
#   session:
#        enabled: true
#        instance: default
#    doctrine:
#        enabled: false
#    router:
#       enabled: false
#       instance: default