imports:
    - { resource: config.yml }

framework:
    profiler: { only_exceptions: false }
    router:
        resource: "%symforium.app_dir%/config/routing_dev.yml"

web_profiler:
    toolbar: true
    intercept_redirects: false