parameters:
    symforium.installer.form.installer.abstract.class: Symforium\Core\Bundle\InstallerBundle\Form\AbstractInstallerForm
    symforium.installer.form.installer.step_one.class: Symforium\Core\Bundle\InstallerBundle\Form\Installer\StepOneForm
    symforium.installer.form.installer.step_two.class: Symforium\Core\Bundle\InstallerBundle\Form\Installer\StepTwoForm
    symforium.installer.form.installer.step_three.class: Symforium\Core\Bundle\InstallerBundle\Form\Installer\StepThreeForm

services:
    symforium.installer.form.installer.abstract:
        class: %symforium.installer.form.installer.abstract.class%
        abstract: true
        arguments:
            - @translator.default

    symforium.installer.form.installer.step_one:
        class: %symforium.installer.form.installer.step_one.class%
        parent: symforium.installer.form.installer.abstract
        tags:
            - { name: form.type, alias: installer_step_one }

    symforium.installer.form.installer.step_two:
        class: %symforium.installer.form.installer.step_two.class%
        parent: symforium.installer.form.installer.abstract
        tags:
            - { name: form.type, alias: installer_step_two }

    symforium.installer.form.installer.step_three:
        class: %symforium.installer.form.installer.step_three.class%
        parent: symforium.installer.form.installer.abstract
        tags:
            - { name: form.type, alias: installer_step_three }
