imports:
    - { resource: forms.yml }
    - { resource: twig.yml }

services:
    symforium.core_bundle.configuration_helper:
        class: Symforium\Bundle\CoreBundle\Service\ConfigurationHelper
        arguments: [@service_container]

    symforium.core_bundle.loader.plugin_route_loader:
        class: Symforium\Bundle\CoreBundle\Loader\PluginRouteLoader
        arguments:
            - %symforium.plugins%
        tags:
            - { name: routing.loader }


    symforium.core_bundle.menu.builder:
        class: Symforium\Bundle\CoreBundle\Menu\Builder
        arguments: [%symforium.plugins%, @knp_menu.factory]

    symforium.menu.admin:
        class: Knp\Menu\MenuItem
        factory_service: symforium.core_bundle.menu.builder
        factory_method: createAdminMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin }

    symforium.listener.doctrine_persistance:
        class: Symforium\Bundle\CoreBundle\Listener\DoctrinePersistanceListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    symforium.listener.exception:
        class: Symforium\Bundle\CoreBundle\Listener\ExceptionListener
        arguments: [@templating]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    symforium.service.router_cache_clearer:
        class: Symforium\Bundle\CoreBundle\Service\RouterCacheClearer
        arguments: [%kernel.cache_dir%]

    router_cache_clearer:
        alias: symforium.service.router_cache_clearer